# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x07predict\"m\n\tDataPoint\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0f\n\x07\x63o_imf1\x18\x02 \x01(\x01\x12\x0f\n\x07\x63o_imf2\x18\x03 \x01(\x01\x12\x0f\n\x07\x63o_imf3\x18\x04 \x01(\x01\x12\x0f\n\x07\x63o_imf4\x18\x05 \x01(\x01\x12\x0e\n\x06target\x18\x06 \x01(\x01\"2\n\x0ePredictRequest\x12 \n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x12.predict.DataPoint\"\x1e\n\x0fPredictResponse\x12\x0b\n\x03val\x18\x01 \x01(\x01\x32I\n\tPredictor\x12<\n\x07Predict\x12\x17.predict.PredictRequest\x1a\x18.predict.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAPOINT']._serialized_start=26
  _globals['_DATAPOINT']._serialized_end=135
  _globals['_PREDICTREQUEST']._serialized_start=137
  _globals['_PREDICTREQUEST']._serialized_end=187
  _globals['_PREDICTRESPONSE']._serialized_start=189
  _globals['_PREDICTRESPONSE']._serialized_end=219
  _globals['_PREDICTOR']._serialized_start=221
  _globals['_PREDICTOR']._serialized_end=294
# @@protoc_insertion_point(module_scope)
